### ISSUE TITLE
Error pinging

### ISSUE THREAD

**Issue by andreafalzetti** [kingsloi/iskingsley.online#5]
I get this message sometimes, generally coming back from a break or when I close the laptop. I think it's not interesting to see this alert, it's more important for me that the application keeps pinging the server as soon as I come back online, but I've noticed the application crashes/stops and I result being offline for long periods until I realize the app is not running anymore!

Did you experience anything like this @kingsloi ?

Thanks for your work!

![screen shot 2016-04-18 at 08 33 30](https://cloud.githubusercontent.com/assets/2318450/14654476/ca0e55aa-0675-11e6-807d-ec516c99291a.png)

**Comment by kingsloi** [comment]
Hey @andreafalzetti,

Sorry about that! I've personally not experienced that, but I think I know what the problem is. I believe when you open your laptop, it attempts to ping before you re-connect to the network/wifi. 

I'm currently re-writing it in [Electron ](http://electron.atom.io/), and there's an API to check for network connectivity, so I'll work that in too. It's all in the develop branch if you're curious. Once it's ready, I'll push it to master and let you know

Cheers buddy!

**Comment by andreafalzetti** [comment]
Great! I'll check it out. Thanks. Keep me posted

**Comment by andreafalzetti** [comment]
I've downloaded and updated with the latest release. The UI for some reasons get stuck and I cannot edit the fields.. Any idea of why? I cannot quit it, so it's impossible to use at the moment :(

**Comment by andreafalzetti** [comment]
FWTW, I had to kill the process and removed the old application. Restarted the new and now it's good! :)

**Comment by kingsloi** [comment]
Hey @andreafalzetti,

Did you download the v3.1.1 release?

**Comment by andreafalzetti** [comment]
Did you use [Electron](http://electron.atom.io/) then?

small issue, the shortcurts cmd+c | cmd+v | cmd+x don't work in the fields

**Comment by kingsloi** [comment]
@andreafalzetti, sorry this fallen off my list. I'm going to relaunch it when I get the time.

**Comment by andreafalzetti** [comment]
no prob @kingsloi - I am moving my domain to a different server so I took the chance to update to the latest release. I wasn't able to install it just replacing the .app file - even using AppCleaner so I just cloned the repo and built it from the source - it worked. Well done in keeping updating the project.
